# Generated by Django 3.2.7 on 2021-11-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.CharField(max_length=500)),
                ('alignments', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
    ]
