# Generated by Django 3.2.7 on 2021-11-30 00:18

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nt_search', '0002_alter_response_alignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='alignments',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
